### ISSUE TITLE
clang-format doesn't like rule in clang-format

### ISSUE THREAD

**Issue by deadbaed** [Wrexes/epitech-clang-format#1]
I downloaded the clang-format file and placed it in my project.

When i indent my file in my ide (vscode on ubuntu), i get this error:

![Screenshot from 2020-02-03 15-04-05](https://user-images.githubusercontent.com/8809909/73660970-885da300-4699-11ea-9fe9-1f11947b7ae1.png)

But when I look at the llvm documentation, it seems that the syntax is correct: 

![Screenshot from 2020-02-03 15-26-40](https://user-images.githubusercontent.com/8809909/73661036-a88d6200-4699-11ea-8b21-3fd02d2819f5.png)

Do you have an idea why this is happening, or you have a fix? I'm still kinda new to clang-format.

Thanks!

**Comment by SirWrexes** [comment]
Yeah I know some rules don't take the same values depending on which system you're on. It might be something version dependent.
Epitech also loves making you use outdated and/or stuff.
Could you go in a terminal, run `clang-format --version` and give me the output ?
To fix the rule you might just need to replace `Never` with `false` though I would honestly recommend [building the latest clang version from source](https://clang.llvm.org/get_started.html).

**Comment by deadbaed** [comment]
`clang-format version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)`

I updated the line to `false` but now im getting errors from other lines....

when you mean building clang, you mean only clang-format or building llvm and clang? thx

**Comment by SirWrexes** [comment]
Just what I thought. Your clang-format is old as hell. Current version is 9.0.1.
I searched for a bit and found out there are up to date LLVM packages on the Ubuntu repositories.
If your Ubuntu is an Epitech dump they surely came bundled with it. try removing them and installing them again yourself with apt.

**Comment by deadbaed** [comment]
Oh okay, I see the issue. I'm on 18.04, so that's why the package is old (god I miss arch).

I had to remove `clang-format` and install `clang-format-9` and symlink `/usr/bin/clang-format` to `/usr/bin/clang-format-9`.

Now everything works as expected! Thanks!

**Comment by SirWrexes** [comment]
Arch Linux master race 💪
Btw you can go back to Arch if you take time to install everything the school requires (CSFML, Criterion, Python 2 and 3, valgrind, gcovr, gdb etc...), which are ALL on either the AUR or official repositories. Just use the Docker image they provide you with in order to make sure what you do works on the autograder.
Anyway, I'm glad the problem is solved. Enjoy easy style friendly coding !

**Comment by deadbaed** [comment]
Well I was running arch for almost 5 years (before I started epitech) and it's great and all but now I kinda stopped taking the time to update and to maintain my system, now I just want something to be stable and that everything just works without tinkering too much.

I say that cause I spent too much time in my tek1 tinkering my system instead of working on the projects haha
